// PRODUCT DATA
export const PRODUCT_ADD = 'PRODUCT_ADD'
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE'
export const PRODUCT_DELETE = 'PRODUCT_DELETE'
export const PRODUCT_LIST = 'PRODUCT_LIST'


// CART DATA
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const CART_TO_WISHLIST = 'CART_TO_WISHLIST'
export const DECREMENT = 'DECREMENT'
export const INCREMENT = 'INCREMENT'


// WISHLIST DATA
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const REMOVE_TO_WISHLIST = 'REMOVE_TO_WISHLIST'
export const EMPTY_WISHLIST = 'EMPTY_WISHLIST'
export const WISHLIST_TO_CART = 'WISHLIST_TO_CART'